services:
  llm:
    image: vllm/vllm-openai:latest
    ports:
      - 8000:8000
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: --model Vikhrmodels/Vikhr-Llama-3.2-1B-Instruct
  
  qdrant:
    image: qdrant/qdrant 
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - /var/lib/qdrant_storage:/qdrant/storage:z


volumes:
  huggingface-cache:
  qdrant-storage:
